rules:
  quoted-strings:
    required: only-when-needed
    extra-allowed: ["{|}"]
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true
  key-duplicates: {}
  octal-values:
    forbid-implicit-octal: true

  # Default line length is 80 characters
  # I prefer disabling this rule entirely
  line-length: disable

ignore:
  # Ignore Helm templates since they aren't "yaml"
  - "**/templates/*.yml"
  - "**/templates/*.yaml"
