name: Pull Request Labeler
on: pull_request_target

permissions: read-all

jobs:
  label_pr:
    permissions:
      contents: read # for actions/labeler to determine modified files
      issues: write # for actions/first-interaction to comment on first issue
      pull-requests: write # for actions/labeler to add labels to PRs
    name: Pull request labeler [linux]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@5c7539237e04b714afd8ad9b4aed733815b9fab4 # v4.0.2
        with:
          repo-token: ${{ github.token }}
          configuration-path: .pr-labels.yaml
          sync-labels: true

      - uses: actions/first-interaction@1d8459ca65b335265f1285568221e229d45a995e # v1.1.1
        with:
          repo-token: ${{ github.token }}
          pr-message:
            👋 Hi @${{ github.actor }}, welcome to Trunk. Congrats 🎉 on opening your first pull
            request!!
